### ISSUE TITLE
TypeError: Object of type type is not JSON serializable

### ISSUE THREAD

**Issue by bp88dev** [aatikturk/obsws-python#50]
### I'm working with the following code and can't get it to work. The title is the error. All I'm doing is trying to hide and show and object, is that too much to ask?

```
cl = obs.ReqClient(host='localhost', port=4455, password='E1W7Y6MpuDf2Bs9o')
audio = cl.get_scene_item_id("Desktop", "Media Source 2", 0)
print(audio)
cl.set_scene_item_enabled("Desktop", audio, False)
```

SHELL SESSION:

```
PS C:\Users\Benji\Documents\kowai> & C:/Users/Benji/AppData/Local/Microsoft/WindowsApps/python3.11.exe c:/Users/Benji/Documents/kowai/scripts/ai.py
Initializing...
<class 'obsws_python.util.GetSceneItemIdDataclass'>
Traceback (most recent call last):
  File "c:\Users\Benji\Documents\kowai\scripts\ai.py", line 81, in <module>
    play()
  File "c:\Users\Benji\Documents\kowai\scripts\ai.py", line 17, in play
    cl.set_scene_item_enabled("Desktop", audio, False)
  File "C:\Users\Benji\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\obsws_python\reqs.py", line 1447, in set_scene_item_enabled
    self.send("SetSceneItemEnabled", payload)
  File "C:\Users\Benji\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\obsws_python\reqs.py", line 51, in send
    response = self.base_client.req(param, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Benji\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\obsws_python\baseclient.py", line 130, in req
    self.ws.send(json.dumps(payload))
                 ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type type is not JSON serializable
PS C:\Users\Benji\Documents\kowai>
```

**Comment by aatikturk** [comment]
Hi,

the problem is here with your code

`audio = cl.get_scene_item_id("Desktop", "Media Source 2", 0)`

`get_scene_item_id` method does not return scene item's id directly.  it returns a class object. you need to access the item id within that class obj like so

```
response = cl.get_scene_item_id("Desktop", "Media Source 2", 0)
audio = response.scene_item_id
```
after that you can use it in your next call

`
cl.set_scene_item_enabled("Desktop", audio, False)
`


actually this is the same for all methods that return a class.  you can check which properties you can access like the example below

![image](https://github.com/user-attachments/assets/fb2eb370-4734-48b3-8bea-f4298645e8bc)


Hope this helps!

**Comment by bp88dev** [comment]
Thanks, that works!
